name: Terraform Deploy or Destroy

on:
  workflow_dispatch:
    inputs:
      customer:
        description: 'Customer name (e.g., customer1)'
        required: true
        type: string

      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

      confirm_destroy:
        description: 'Type "CONFIRM" to allow destroy (case-sensitive)'
        required: false
        default: ''


jobs:
  terraform:
    name: Terraform ${{ inputs.action }} on ${{ inputs.customer }} / ${{ inputs.environment }}
    runs-on: ubuntu-latest

    # 🔒 Apply environment only for `destroy` to trigger approval
    environment: ${{ inputs.action == 'destroy' && inputs.environment || '' }}

    # 🛑 Only allow destroy if confirmation is typed
    if: ${{ inputs.action != 'destroy' || inputs.confirm_destroy == 'CONFIRM' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3

      - name: Terraform Format Check
        working-directory: stacks/${{ inputs.customer }}
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: stacks/${{ inputs.customer }}
        run: terraform init -input=false

      - name: Terraform Validate
        if: ${{ inputs.action == 'apply' || inputs.action == 'plan' }}
        working-directory: stacks/${{ inputs.customer }}
        run: terraform validate

  
