name: Terraform Deploy or Destroy

on:
  workflow_dispatch:
    inputs:
      customer:
        description: 'Customer name (e.g., customer1)'
        required: true
        type: string

      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - apply
          - destroy

      environment:
        description: 'Environment (e.g., dev, prod)'
        required: true
        type: string

      confirm_destroy_prod:
        description: 'Type "CONFIRM" to destroy PROD environment (case-sensitive)'
        required: false
        default: ''

env:
  AWS_REGION: us-west-2

jobs:
  terraform:
    name: Terraform ${{ inputs.action }} on ${{ inputs.customer }} / ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    # Only allow destroy in prod if explicitly confirmed
    if: ${{ inputs.action != 'destroy' || inputs.environment != 'prod' || inputs.confirm_destroy_prod == 'CONFIRM' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - na
