name: Terraform Deploy or Destroy

on:
  workflow_dispatch:
    inputs:
      customer:
        description: 'Customer name (e.g., customer1)'
        required: true
        type: string

      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

      confirm_destroy:
        description: 'Type "CONFIRM" to allow destroy (case-sensitive)'
        required: false
        default: ''


jobs:
  terraform:
    name: Terraform ${{ inputs.action }} on ${{ inputs.customer }} / ${{ inputs.environment }}
    runs-on: ubuntu-latest

    # 🔒 Apply environment only for `destroy` to trigger approval
    environment: ${{ inputs.action == 'destroy' && inputs.environment || '' }}

    # 🛑 Only allow destroy if confirmation is typed
    if: ${{ inputs.action != 'destroy' || inputs.confirm_destroy == 'CONFIRM' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1    

      - name: Terraform Format Check
        working-directory: stacks/${{ inputs.customer }}
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: stacks/${{ inputs.customer }}
        run: |
               terraform init -input=false \
               -backend-config="terraformbackup020625" \
               -backend-config="key=${{ inputs.customer }}/${{ inputs.environment }}/terraform.tfstate" \
               -backend-config="region=us-east-1"

      - name: Terraform Validate
        if: ${{ inputs.action == 'apply' || inputs.action == 'plan' }}
        working-directory: stacks/${{ inputs.customer }}
        run: terraform validate


  
